<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="2dof_arm">

    <!-- \\\\\\ Build 2DoF Arm Robot \\\\\\ -->

    <!-- \\\ Include Parameters and Macros \\\ -->
    <xacro:include filename="$(find robot_2dof)/models/params_macro.xacro"/>

    <!-- Chassis Link: Fictitious Link -->
    <link name = "world"/>

    <joint name="world_joint" type="fixed">
        <origin xyz="0 0 ${base_height}" rpy="0 0 0" />
        <parent link="world"/>
        <child link="chassis"/>
    </joint>

    <!--Chassis-->
    <xacro:cylinder_link name="chassis" length="${base_height}" radius="${base_width/2}" 
                            mass="${m_base}" colour="Black"/>

    <!--Link 1-->
    <xacro:cylinder_link name="link1" length="${a1}" radius="${r1}" 
                            z="${a1/2}" mass="${m1}" colour="White"
                            cogz="${a1/2}"/>

    <!-- Joint 1-->
    <joint name="joint_1" type="revolute">
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        <parent link="chassis"/>
        <child link="link1"/>
        <axis xyz="0 1 0"/>
        <limit effort="${joint_effort}" velocity="${joint_vel}" lower="${-joint_limit}" upper="${joint_limit}"/>
    </joint>

    <!--Link 2-->
    <xacro:cylinder_link name="link2" length="${a2}" radius="${r2}" 
                            z="${a2/2}" mass="${m2}" colour="Red"
                            cogz="${a2/2}"/>

    
    <!-- Joint 2-->
    <joint name="joint_2" type="revolute">
        <origin xyz="0 0 ${a1}" rpy="0 0 0"/>
        <parent link="link1"/>
        <child link="link2"/>
        <axis xyz="0 1 0"/>
        <limit effort="${joint_effort}" velocity="${joint_vel}" lower="${-joint_limit}" upper="${joint_limit}"/>
        <dynamics damping="0.0"/>
    </joint>

    <!-- \\\ Actuation \\\ -->
    <xacro:transmission_block joint_name="joint_1" location="1"/>
    <xacro:transmission_block joint_name="joint_2" location="2"/>

    <!-- \\\\\\ GAZEBO Plugins \\\\\\ -->
    <!-- ros_control plugin -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/2dof_arm</robotNamespace>
        </plugin>
    </gazebo>
</robot>
